spec-version: 0.30.0
name: elect
author: Asad Saeeduddin
maintainer: masaeedu@gmail.com
license: MIT

build-type: Simple

dependencies:
- { name: "base", version: '>=4.14 && <4.15' }

ghc-options: -Wall
default-extensions:
- GADTs

- StandaloneDeriving
- DeriveFunctor
- DerivingVia
- GeneralizedNewtypeDeriving

- ScopedTypeVariables
- RankNTypes
- QuantifiedConstraints

- TypeApplications
- TypeOperators
- MultiParamTypeClasses

- ConstraintKinds
- DataKinds
- PolyKinds
- KindSignatures

- UndecidableInstances
- FlexibleInstances
- FlexibleContexts
- DefaultSignatures

library:
  source-dirs: lib
  dependencies:
  - these
  - bifunctors
  - semirings

tests:
  test:
    source-dirs: test
    main: Main.hs
    dependencies:
    - elect
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - QuickCheck
    - quickcheck-classes
    - generic-random
    build-tools:
    - tasty-discover
